### ISSUE TITLE
Error when training extractor

### ISSUE THREAD

**Issue by liug0324** [ChenRocks/fast_abs_rl#18]
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 190, in get_context
    ctx = _concrete_contexts[method]
KeyError: 'forkserver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/lab/2018match/fast_abs_rl-master/fast_abs_rl-master/train_extractor_ml.py", line 237, in <module>
    main(args)
  File "D:/lab/2018match/fast_abs_rl-master/fast_abs_rl-master/train_extractor_ml.py", line 131, in main
    args.cuda, args.debug)
  File "D:/lab/2018match/fast_abs_rl-master/fast_abs_rl-master/train_extractor_ml.py", line 71, in build_batchers
    single_run=False, fork=not debug)
  File "D:\lab\2018match\fast_abs_rl-master\fast_abs_rl-master\data\batcher.py", line 216, in __init__
    ctx = mp.get_context('forkserver')
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 238, in get_context
    return super().get_context(method)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 192, in get_context
    raise ValueError('cannot find context for %r' % method)
ValueError: cannot find context for 'forkserver'

**Comment by Zierzzz** [comment]
> Traceback (most recent call last):
> File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 190, in get_context
> ctx = _concrete_contexts[method]
> KeyError: 'forkserver'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "D:/lab/2018match/fast_abs_rl-master/fast_abs_rl-master/train_extractor_ml.py", line 237, in 
> main(args)
> File "D:/lab/2018match/fast_abs_rl-master/fast_abs_rl-master/train_extractor_ml.py", line 131, in main
> args.cuda, args.debug)
> File "D:/lab/2018match/fast_abs_rl-master/fast_abs_rl-master/train_extractor_ml.py", line 71, in build_batchers
> single_run=False, fork=not debug)
> File "D:\lab\2018match\fast_abs_rl-master\fast_abs_rl-master\data\batcher.py", line 216, in **init**
> ctx = mp.get_context('forkserver')
> File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 238, in get_context
> return super().get_context(method)
> File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 192, in get_context
> raise ValueError('cannot find context for %r' % method)
> ValueError: cannot find context for 'forkserver'
Hello ，I also met this question and could you tell me how you solved it？

**Comment by florian-boehm** [comment]
According to the [documentation](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods) of the multiprocessing library 'forkserver' is only available under UNIX systems. I am currently running the extractor/abstractor training under Windows 10 with the 'spawn' context. It seems to work fine so far.

**Comment by ChenRocks** [comment]
I think @florian-boehm 's suggestion should fix this. Thanks!

I only tested on Linux so for Windows you can try the fix. Currently there's no plan to make the code Windows compatible though.
