### ISSUE TITLE
No such file or directory: 'path/to/raw-stories/val'

### ISSUE THREAD

**Issue by ishandutta2007** [ChenRocks/fast_abs_rl#23]
**Where should I create val/test folder ?** 

I am trying to evaluate from pretrained model. As per the instructions after downloaing and detokenising the dataset I get,

- Prretrained model folder
- */stories folder
- *_stories_tokenized folder

ishandutta2007@MacBook-Pro:~/Documents/Projects/fast_abs_rl$ `export DATA=../cnn-dailymail/cnn/stories`

ishandutta2007@MacBook-Pro:~/Documents/Projects/fast_abs_rl$ `python decode_full_model.py --path=../cnn-dailymail/cnn_stories_tokenized  --model_dir=./pretrained/acl  --beam=5 --val`

> loading checkpoint ckpt-0-0...
> loading checkpoint ckpt-42.508549-0...
> Traceback (most recent call last):
>   File "decode_full_model.py", line 169, in <module>
>     args.max_dec_word, args.cuda)
>   File "decode_full_model.py", line 49, in decode
>     dataset = DecodeDataset(split)
>   File "/Users/ishandutta2007/Documents/Projects/fast_abs_rl/decoding.py", line 30, in __init__
>     super().__init__(split, DATASET_DIR)
>   File "/Users/ishandutta2007/Documents/Projects/fast_abs_rl/data/data.py", line 14, in __init__
>     self._n_data = _count_data(self._data_path)
>   File "/Users/ishandutta2007/Documents/Projects/fast_abs_rl/data/data.py", line 29, in _count_data
>     names = os.listdir(path)
> FileNotFoundError: [Errno 2] No such file or directory: '../cnn-dailymail/cnn/stories/val'

**Comment by ishandutta2007** [comment]
Solved it myself, I missed the instructions, besides above three kinds of foldera there is `finished_files` folder generated as well where test.tar, train.tar, val.tar is present. We just have to unpack them and export like this(assunmg unpacked under `finished_files/val`):


`export DATA=../cnn-dailymail/finished_files`
