### ISSUE TITLE
RuntimeError: Expected tensor for argument #1 'input' to have the same dimensionas tensor for 'result'

### ISSUE THREAD

**Issue by EddieWang0317** [ChenRocks/fast_abs_rl#25]
```
Traceback (most recent call last):
  File "train_extractor_ml.py", line 237, in <module>
    main(args)
  File "train_extractor_ml.py", line 179, in main
    trainer.train()
  File "/home/eddiewng/LCSTS/fast_abs_rl/training.py", line 211, in train
    log_dict = self._pipeline.train_step()
  File "/home/eddiewng/LCSTS/fast_abs_rl/training.py", line 96, in train_step
    net_out = self._net(*fw_args)
  File "/home/eddiewng/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eddiewng/LCSTS/fast_abs_rl/model/extract.py", line 276, in forward
    enc_out = self._encode(article_sents, sent_nums)
  File "/home/eddiewng/LCSTS/fast_abs_rl/model/extract.py", line 296, in _encode
    for art_sent in article_sents]
  File "/home/eddiewng/LCSTS/fast_abs_rl/model/extract.py", line 296, in <listcomp>
    for art_sent in article_sents]
  File "/home/eddiewng/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eddiewng/LCSTS/fast_abs_rl/model/extract.py", line 31, in forward
    for conv in self._convs], dim=1)
  File "/home/eddiewng/LCSTS/fast_abs_rl/model/extract.py", line 31, in <listcomp>
    for conv in self._convs], dim=1)
  File "/home/eddiewng/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eddiewng/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 176, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected tensor for argument #1 'input' to have the same dimension as tensor for 'result'; but 4 does not equal 3 (while checking arguments for cudnn_convolution)
```

I am trying to implement the model on chinese dataset. I succeeded to train the abstractive model. But when i try to train the extractive model. It just throw out this error. I have no idea what's going on. Does any one have any idea?

**Comment by ChenRocks** [comment]
It seems like you have some bugs in data preprocessing so the input shape is wrong. I can't diagnose the exact problem base on what you provided. Please maybe share a sample of the preprocessed Chinese data then I can try to help. Thanks.

**Comment by ChenRocks** [comment]
Our current plan is only to maintain this research code base for CNN/DM dataset and since there's no further discussion I'm closing this issue. 

Feel free to reopen if you have some new ideas. I'm happy to discuss with you.

**Comment by sakusss** [comment]
Hi I have met the same error trained on LCSTS data ,and I wonder whether you  have solved the question?
