### ISSUE TITLE
Error: AttributeError: 'float' object has no attribute 'item'.

### ISSUE THREAD

**Issue by jawdat23** [ChenRocks/fast_abs_rl#26]
Hey,
Thank you very much for this great work.
i am having this error when I train my abstractor model:
AttributeError: 'float' object has no attribute 'item'.
any ideas why ?
Thanks in advanced

**Comment by QiuJun1994** [comment]
I hava the same problem

**Comment by jawdat23** [comment]
it is already solved in the closed issues

**Comment by graceyue** [comment]
but I still met this issue, and i search the solution is pytorch must be 0.4?
Please help, thanks a lot.

**Comment by ChenRocks** [comment]
my quick guess is to delete this [line](https://github.com/ChenRocks/fast_abs_rl/blob/b1b66c180a135905574fdb9e80a6da2cabf7f15c/training.py#L20)

Please let me know if it works and your pytorch version. I think pytorch 1.0 has some API change from 0.4 so some small things might break.

**Comment by graceyue** [comment]
I rolled back pytorch 1.0 to 0.4.0…..

And now I run the code on windows with CPU and met the issue, that is because the code cant run windows with multiprocessing
Thanks a lot!

Traceback (most recent call last):
  File "D:/Projects/fast_abs_rl-master/decode_full_model.py", line 164, in <module>
    args.max_dec_word, args.cuda)
  File "D:/Projects/fast_abs_rl-master/decode_full_model.py", line 67, in decode
    for i_debug, raw_article_batch in enumerate(loader):
  File "D:\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    w.start()
  File "D:\anaconda3\envs\pytorch\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\anaconda3\envs\pytorch\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\anaconda3\envs\pytorch\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\anaconda3\envs\pytorch\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\anaconda3\envs\pytorch\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'decode.<locals>.coll'

**Comment by ChenRocks** [comment]
Unfortunately Windows is not supported and I don't plan to support Windows in the near future. Also, running on CPU will take extremely long time which is not recommended. Please try to find some Ubuntu system with GPU that you can use.
