### ISSUE TITLE
RuntimeError: sizes must be non-negative

### ISSUE THREAD

**Issue by jawdat23** [ChenRocks/fast_abs_rl#34]
Hey,
Thank you very much for this great work,
I am having a problem training extractor model on my own data,
I am using pytorch 0.4.0 with Cuda 10.0 on Ubuntu 18.04
I hope you can help me with this issue.
Thank you very much in advanced.

this is the error traceback:

Traceback (most recent call last):
  File "/home/me/fast_abs_rl-master/model/extract.py", line 33, in forward
    for conv in self._convs], dim=1)
  File "/home/me/fast_abs_rl-master/model/extract.py", line 33, in <listcomp>
    for conv in self._convs], dim=1)
  File "/home/me/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/me/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 176, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: sizes must be non-negative

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_extractor_ml.py", line 237, in <module>
    main(args)
  File "train_extractor_ml.py", line 179, in main
    trainer.train()
  File "/home/me/fast_abs_rl-master/training.py", line 212, in train
    log_dict = self._pipeline.train_step()
  File "/home/me/fast_abs_rl-master/training.py", line 97, in train_step
    net_out = self._net(*fw_args)
  File "/home/me/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/me/fast_abs_rl-master/model/extract.py", line 287, in forward
    enc_out = self._encode(article_sents, sent_nums)
  File "/home/me/fast_abs_rl-master/model/extract.py", line 309, in _encode
    for art_sent in article_sents]
  File "/home/me/fast_abs_rl-master/model/extract.py", line 309, in <listcomp>
    for art_sent in article_sents]
  File "/home/me/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/me/fast_abs_rl-master/model/extract.py", line 40, in forward
    for conv in self._convs])
  File "/home/me/fast_abs_rl-master/model/extract.py", line 40, in <listcomp>
    for conv in self._convs])
  File "/home/me/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/me/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 176, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: sizes must be non-negative

**Comment by jawdat23** [comment]
I solved the problem, it is due to the fact that there is a problem in my input data.

**Comment by ChenRocks** [comment]
Thanks for your interest in this project. Unfortunately without seeing the data there is no way to debug. I will try my best to help if you could provide some data samples.

**Comment by jawdat23** [comment]
Thank you for your reply, my data set is pretty much the same as CNN/DM articles.
here are some stats of my data:
I have 20000 articles, having maximum of 50 paragraphs and 1 paragraph minimum. each paragraph has 26 to 1860 characters. 
and each article has one paragraph abstract only, which is the article title.
the abstractor model worked perfectly. 

here is a link to one of the articles sample:
https://www.dropbox.com/s/jsq6wyoxud3rsv0/8988.json?dl=0

P.S: I did a data shuffling, and got a new error.

Traceback (most recent call last):
  File "/home/me/fast_abs_rl-master/model/extract.py", line 33, in forward
    for conv in self._convs], dim=1)
  File "/home/mefast_abs_rl-master/model/extract.py", line 33, in <listcomp>
    for conv in self._convs], dim=1)
  File "/home/me/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/me/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 176, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Calculated padded input size per channel: (1 x 3). Kernel size: (1 x 4). Kernel size can't be greater than actual input size at /pytorch/aten/src/THNN/generic/SpatialConvolutionMM.c:48

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_extractor_ml.py", line 237, in <module>
    main(args)
  File "train_extractor_ml.py", line 179, in main
    trainer.train()
  File "/home/me/fast_abs_rl-master/training.py", line 212, in train
    log_dict = self._pipeline.train_step()
  File "/home/mes/fast_abs_rl-master/training.py", line 97, in train_step
    net_out = self._net(*fw_args)
  File "/home/me/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/me/fast_abs_rl-master/model/extract.py", line 287, in forward
    enc_out = self._encode(article_sents, sent_nums)
  File "/home/me/fast_abs_rl-master/model/extract.py", line 309, in _encode
    for art_sent in article_sents]
  File "/home/me/fast_abs_rl-master/model/extract.py", line 309, in <listcomp>
    for art_sent in article_sents]
  File "/home/me/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/me/fast_abs_rl-master/model/extract.py", line 40, in forward
    for conv in self._convs])
  File "/home/me/jawdat/projects/fast_abs_rl-master/model/extract.py", line 40, in <listcomp>
    for conv in self._convs])
  File "/home/me/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/me/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 176, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Calculated padded input size per channel: (1 x 3). Kernel size: (1 x 4). Kernel size can't be greater than actual input size at /pytorch/aten/src/THNN/generic/SpatialConvolutionMM.c:48

**Comment by ChenRocks** [comment]
Please check the articles in your dataset. Is there any sentences having less than 5 words? Removing them could probably solve the issue.

Our algorithm tries to select important sentences to summarize, so those short sentences is probably not very important. Because our convolution uses kernel size 3, 4, 5, the sentences must be at least 5 words.

**Comment by jawdat23** [comment]
Thank you very much, that was my problem.
and thanks again for this great work.
