### ISSUE TITLE
RuntimeError: Expected tensor for argument #1 'input' to have the same dimension as tensor for 'result'; but 4 does not equal 3

### ISSUE THREAD

**Issue by shellycsy** [ChenRocks/fast_abs_rl#56]
Hello,thank you for sharing!

  when I use dilation convolution to extract features,The following problem has occurred:
  RuntimeError: Expected tensor for argument #1 'input' to have the same dimension as tensor for 'result'; but 4 does not equal 3 (while checking arguments for cudnn_convolution)

  and I print the emb_input.size in the /model/extract.py line 27, I found the torch is ([60, 6, 128]) when the problem occured.I guess because the value of the second dimension is too small, it leads to an error. In other normal cases, the value of the second dimension is not so small.
    can you tell me the meaning of the value of the second dimension?If it is not for this reason, do you know why?
    thank you !

**Comment by shellycsy** [comment]
Traceback (most recent call last):
  File "train_extractor_ml.py", line 241, in <module>
    main(args)
  File "train_extractor_ml.py", line 183, in main
    trainer.train()
  File "/home/csy/fast_abs_rl/training.py", line 211, in train
    log_dict = self._pipeline.train_step()
  File "/home/csy/fast_abs_rl/training.py", line 96, in train_step
    net_out = self._net(*fw_args)
  File "/home/csy/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/csy/fast_abs_rl/model/extract.py", line 300, in forward
    enc_out = self._encode(article_sents, sent_nums)
  File "/home/csy/fast_abs_rl/model/extract.py", line 320, in _encode
    for art_sent in article_sents]
  File "/home/csy/fast_abs_rl/model/extract.py", line 320, in <listcomp>
    for art_sent in article_sents]
  File "/home/csy/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/csy/fast_abs_rl/model/extract.py", line 41, in forward
    conv2=F.relu(self._dia_convs23(conv_in)).max(dim=2)[0]
  File "/home/csy/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/csy/anaconda3/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 176, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected tensor for argument #1 'input' to have the same dimension as tensor for 'result'; but 4 does not equal 3 (while checking arguments for cudnn_convolution)

**Comment by nickluijtgaarden** [comment]
I think the problem is related to the fact that sentences need to be > 5
words, as the convolutional model looks at the context of words.

Op zo 7 jul. 2019 11:10 schreef shellycsy <notifications@github.com>:

**Comment by shellycsy** [comment]
I tried to remove the sentence with a length less than 30, but it still didn't work, and there was a problem in the same place.

**Comment by shellycsy** [comment]
> I think the problem is related to the fact that sentences need to be > 5
> words, as the convolutional model looks at the context of words.
> 
> Op zo 7 jul. 2019 11:10 schreef shellycsy <notifications@github.com>:
> …

I tried to remove the sentence with a length less than 30, but it still didn't work, and there was a problem in the same place.

**Comment by ChenRocks** [comment]
Seems like you modified the code with some dilated convolution? I probably don't have time to help everyone with their modification for new research but feel free to share codes and discuss with others.

**Comment by ChenRocks** [comment]
closing this due to inactivity

**Comment by sakusss** [comment]
hello I have met the same error.Have you solve the problem? @shellycsy

**Comment by iasonasxrist** [comment]
same problem but fixed with command `.float()`.
This error  referred to the` tensor.dtype` such as `torch.float16` is the half tensor of `tensor.float32`!
