### ISSUE TITLE
Can't use without CUDA (GPU)

### ISSUE THREAD

**Issue by pbeneteau** [ChenRocks/fast_abs_rl#63]
Hi,

I'm unable to launch it without CUDA. I should be able to use my CPU only...

```
python3 decode_full_model.py --path=decoded_files/ --model_dir=../models/pretrained/new/ --beam=5 --val --no-cuda

loading checkpoint ckpt-0-0...
Traceback (most recent call last):
  File "decode_full_model.py", line 169, in <module>
    args.max_dec_word, args.cuda)
  File "decode_full_model.py", line 42, in decode
    max_len, cuda)
  File "/fast_abs_rl/decoding.py", line 69, in __init__
    abs_ckpt = load_best_ckpt(abs_dir)
  File "/fast_abs_rl/decoding.py", line 53, in load_best_ckpt
    join(model_dir, 'ckpt/{}'.format(ckpts[0]))
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 702, in _legacy_load
    result = unpickler.load()
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 665, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 156, in default_restore_location
    result = fn(storage, location)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 132, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/usr/local/lib/python3.7/site-packages/torch/serialization.py", line 116, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

**Comment by alyaa278** [comment]
How did you solve this problem?
